# 服务配置
Server:
  # 监听地址
  Address: 0.0.0.0
  # 监听端口
  Port: 9527
  # 上下文路径
  Context: "/webhook"

WebHook:
  # 默认为 application/json , 若是旧版钩子(已不维护)为 application/x-www-form-urlencoded
  ContentType: application/json
  # 固定为 git-oschina-hook，可用于标识为来自 gitee 的请求
  UserAgent: git-oschina-hook
  # 用户新建 WebHook 时提供的密码或根据提供的签名密钥计算后的签名
  Token: abon123

Logger:
  # 日志默认级别，值必须是：debug,info,warn,error，默认值是info
  LogLevel: "debug"
  # 日志存储路径
  LogDir: "./logs"

